from module1 import is_TamGiac,ChuviTamGiac,S_TamGiac
from module1 import chuviHinhVuong,Dien_tich_hinh_vuong
from module3 import ucln,bcnn
from module4 import pt_bac_nhat_1_an,pt_bac_2
from module5 import he_nhi_phan,he_bat_phan,he_thap_luc_phan
from module2 import dayso,snto,snto_chia_cho7,tong
from module2 import nhapdulieu,in_ma_tran,mt_chuyen_vi,kiem_tra_doi_xung
from module6 import test,kiem_tra,mot,hai,ba
from module9 import nhap_hang_hoa,sap_xep_theo_thue