from .mod1 import is_TamGiac,ChuviTamGiac,S_TamGiac
from .mod2 import ChuviHinhvuong,DientichHinhvuong
from .mod3 import ucln,bcnn
from .mod4 import pt_bac_nhat_1_an,pt_bac_2
from .mod5 import input,he_nhi_phan,he_bat_phan,he_thap_luc_phan
from .mod6 import xoa_kt_ko_hop_le,cs2_to_cs10,cs8_to_cs10
from .mod7 import day_so,list_7,sum_odd
from .mod8 import input_matrix,print_matrix,is_symmetric,transpose_matrix
from .mod9 import input_item_info,print_item_info,calculate_total_price
from .mod10 import is_TamGiac,ChuviTamGiac,S_TamGiac,ChuviHinhVuong,DientichHinhVuong
from .mod11 import in_ra,cs01,cs8p,cs16p,xoa_kt_ko_hop_le,cs2_to_cs10,cs8_to_cs10