msv = int(input("Nhập mã số sinh viên: "))
ht = input("Nhập họ tên: ")
qq = input("Nhập quê quán: ")
ns = int(input("Nhập năm sinh: "))
dtb = float(input("Nhập điểm trung bình các năm học: "))
print(f"Mã sinh viên: {msv}")
print(f"Họ tên: {ht}")
print(f"Quê quán: {qq}")
print(f"Năm sinh: {ns}")

print(f"Điểm trung bình các năm: {dtb}") 