msv=input('Nhập mã số sinh viên :')
ht = input('Nhập họ tên :')
qq= input('Nhập quê quán :')
ns= input('Nhập năm sinh :')
dtb=input('Nhập điểm trung bình các năm học :')
print('Mã số sinh viên là :',msv)
print('Họ tên là :',ht)
print('Quê quán là :',qq)
print('Năm sinh là :',ns)
print('Điểm trung bình các năm học là :',dtb)

