Ax = float(input("Nhập Ax: "))
Ay = float(input("Nhập Ay: "))
Bx = float(input("Nhập Bx: "))
By = float(input("Nhập By: "))
Cx = float(input("Nhập Cx: "))
Cy = float(input("Nhập Cy: "))
Gx = round((Ax + Bx + Cx) / 3, 2)
Gy = round((Ay + By + Cy) / 3, 2)
print("Trong tam tam giac la:",Gx,Gy)