x = int(input("nhập điểm tọa độ oyz:"))
y = int(input("nhập điểm tọa độ oxz:"))
z = int(input("nhập điểm tọa độ oxy:"))
toa_do_x = (-x,y,z)
toa_do_y = (x,-y,z)
toa_do_z = (x,y,-z)
print("tọa độ đối xứng của x",toa_do_x)
print("tọa độ đối xứng của y",toa_do_y)
print("tọa độ đối xứng của x",toa_do_z)