ma_so = input("Nhập mã số sinh viên: ")
ho_ten = input("Nhập họ và tên sinh viên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = input("Nhập năm sinh: ")
diem_tb = float(input("Nhập điểm trung bình các năm học: "))
print("--------------------------")
print("Thông tin sinh viên:")
print("Mã số sinh viên:", ma_so)
print("Họ và tên sinh viên:", ho_ten)
print("Quê quán:", que_quan)
print("Năm sinh:", nam_sinh)
print("Điểm trung bình các năm học:", diem_tb)