x = int(input("Nhập x: "))
y = int(input("Nhập y: "))
z = int(input("Nhập z: "))
doi_xung_qua_Oxy = (x,y,-z)
doi_xung_qua_Oxz = (x,-y,z)
doi_xung_qua_Oyz = (-x,y,z)
print("Toạ độ điểm đối xứng qua Oxy: ", doi_xung_qua_Oxy)
print("Toạ độ điểm đối xứng qua Oxz: ", doi_xung_qua_Oxz)
print("Toạ độ điểm đối xứng qua Oyz: ", doi_xung_qua_Oyz)