x = int(input("Nhap x: "))
y = int(input("Nhap y: "))
z = int(input("Nhap z: "))
doi_xung_qua_Oxy = (x,y,-z)
doi_xung_qua_Oxz = (x,-y,z)
doi_xung_qua_Oyz = (-x,y,z)
print("Toa do cua diem doi xung qua Oxy: ", doi_xung_qua_Oxy)
print("Toa do cua diem doi xung qua Oxz: ", doi_xung_qua_Oxz)
print("Toa do cua diem doi xung qua Oyz: ", doi_xung_qua_Oyz)