x=int(input('Nhap toa do x: '))
y=int(input('Nhap toa do y: '))
z=int(input('Nhap toa do z: '))
print(f'Toa do diem doi xung qua Oxy la {x,y,-z}')
print(f'Toa do diem doi xung qua Oxz la {x,-y,z}')
print(f'Toa do diem doi xung qua Oyz la {-x,y,z}')